name: sfs_editor
description: "A new Flutter project."
# publish_to: 'none'

version: 1.0.0+28

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_editor_plus:
    path: ./image_editor_plus/
  
  cupertino_icons: ^1.0.8
  appcheck: ^1.5.2
  url_launcher: ^6.2.6
  snapkit_flutter: ^0.0.1
  google_mobile_ads: ^5.0.0
  webview_flutter: ^4.6.0
  equatable: ^2.0.5
  purchases_flutter: ^6.30.2
  image_picker: ^1.0.8
  image_gallery_saver: ^2.0.3
  share_plus: ^9.0.0
  video_trimmer: ^3.0.1
  video_player: ^2.8.6
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  dots_indicator: ^3.0.0
  file_picker: ^8.0.3
  http: ^1.2.1
  flutter_screenutil: ^5.9.1
  provider: ^6.1.2
  flutter_image_compress: ^2.3.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  image: ^4.2.0
  intl: ^0.18.1
  in_app_review: ^2.0.9
  flutter_email_sender: ^6.0.3
  screenshot: ^3.0.0
  connectivity_plus: ^6.0.5
  # snapkit: ^1.1.0

module:
  androidPackage: com.example.sfs_editor
  iosBundleIdentifier: com.example.sfs_editor
  androidX: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/instalogo.png
    - assets/finalwplogo.png
    - assets/video.png
    - assets/icons/
    - assets/youtube.png
    - assets/starryImages/
    - assets/getimgimages/
    - assets/videos/
    - assets/pricingimages/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
